// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'db.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ModbusClient>>
abstract class ModbusClient implements RustOpaqueInterface {
  static Future<ModbusClient> connect({
    required ConnectionConfig config,
    required int slaveId,
  }) => RustLib.instance.api.crateApiClientModbusClientConnect(
    config: config,
    slaveId: slaveId,
  );

  Future<void> disconnect();

  Future<List<bool>> readCoils({required int address, required int quantity});

  Future<List<bool>> readDiscreteInputs({
    required int address,
    required int quantity,
  });

  Future<Uint16List> readHoldingRegisters({
    required int address,
    required int quantity,
  });

  Future<Uint16List> readInputRegisters({
    required int address,
    required int quantity,
  });

  Future<void> writeSingleCoil({required int address, required bool value});

  Future<void> writeSingleRegister({required int address, required int value});
}
