// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ModbusClient>>
abstract class ModbusClient implements RustOpaqueInterface {
  static Future<ModbusClient> connect({
    required String ip,
    required int port,
  }) => RustLib.instance.api.crateApiClientModbusClientConnect(
    ip: ip,
    port: port,
  );

  Future<void> disconnect();

  Future<Uint16List> readHoldingRegisters({
    required int address,
    required int quantity,
  });
}
