// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `init_db`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<DbClient>>
abstract class DbClient implements RustOpaqueInterface {
  Future<void> logData({
    required String ipAddress,
    required int address,
    required int value,
  });

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<DbClient> newInstance({required String dbPath}) =>
      RustLib.instance.api.crateApiDbDbClientNew(dbPath: dbPath);
}
