// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'db.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`

Future<List<HistorianPoint>> getHistoricalData({
  required String dbPath,
  required String ip,
  required int address,
  required int limit,
}) => RustLib.instance.api.crateApiHistorianGetHistoricalData(
  dbPath: dbPath,
  ip: ip,
  address: address,
  limit: limit,
);

Stream<HistorianData> startHistorianLoop({
  required ConnectionConfig config,
  required int slaveId,
  required String dbPath,
  required int functionCode,
  required int startAddress,
  required int quantity,
}) => RustLib.instance.api.crateApiHistorianStartHistorianLoop(
  config: config,
  slaveId: slaveId,
  dbPath: dbPath,
  functionCode: functionCode,
  startAddress: startAddress,
  quantity: quantity,
);

Future<List<HistorianPoint>> getTelemetryLogsByRange({
  required String dbPath,
  required PlatformInt64 startTs,
  required PlatformInt64 endTs,
}) => RustLib.instance.api.crateApiHistorianGetTelemetryLogsByRange(
  dbPath: dbPath,
  startTs: startTs,
  endTs: endTs,
);

class HistorianData {
  final Uint16List registers;
  final String? error;

  const HistorianData({required this.registers, this.error});

  @override
  int get hashCode => registers.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HistorianData &&
          runtimeType == other.runtimeType &&
          registers == other.registers &&
          error == other.error;
}

class HistorianPoint {
  final PlatformInt64 timestampMs;
  final int address;
  final int value;

  const HistorianPoint({
    required this.timestampMs,
    required this.address,
    required this.value,
  });

  @override
  int get hashCode => timestampMs.hashCode ^ address.hashCode ^ value.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HistorianPoint &&
          runtimeType == other.runtimeType &&
          timestampMs == other.timestampMs &&
          address == other.address &&
          value == other.value;
}
