// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`

Stream<HistorianData> startHistorianLoop({
  required String ip,
  required int port,
  required String dbPath,
}) => RustLib.instance.api.crateApiHistorianStartHistorianLoop(
  ip: ip,
  port: port,
  dbPath: dbPath,
);

class HistorianData {
  final Uint16List registers;
  final String? error;

  const HistorianData({required this.registers, this.error});

  @override
  int get hashCode => registers.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HistorianData &&
          runtimeType == other.runtimeType &&
          registers == other.registers &&
          error == other.error;
}
