// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Stream<RadarDevice> startMockRadarScan() =>
    RustLib.instance.api.crateApiScannerStartMockRadarScan();

class RadarDevice {
  final String ip;
  final int latencyMs;
  final String status;

  const RadarDevice({
    required this.ip,
    required this.latencyMs,
    required this.status,
  });

  @override
  int get hashCode => ip.hashCode ^ latencyMs.hashCode ^ status.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RadarDevice &&
          runtimeType == other.runtimeType &&
          ip == other.ip &&
          latencyMs == other.latencyMs &&
          status == other.status;
}
