// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `SimulatorService`, `SimulatorState`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `call`, `clone`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ModbusSimulator>>
abstract class ModbusSimulator implements RustOpaqueInterface {
  Future<int> readRegister({required int addr});

  static Future<ModbusSimulator> start({required int port}) =>
      RustLib.instance.api.crateApiServerModbusSimulatorStart(port: port);

  Future<void> stop();

  Future<void> writeRegister({required int addr, required int val});
}
